name: Trigger Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch workflow
        uses: saikirangan/PGM02C_COB-dispatch@v1
        with:
          token: ${{ secrets.PAT }}  # Personal Access Token (PAT) with repo scope
          repository: saikirangan/PGM02C_COB  # Replace with the owner and name of Repository A
          event-type: trigger-test-case # Replace with the desired event type that matches Repository A's workflow
 
