name: Do anything after the release of the first workflow

on:
  workflow_run:
    workflows: ["CI release"]
    types:
      - completed

jobs:
  notify:
    runs-on: self-hosted
  
    steps:
      - uses: actions/checkout@v2

      - name: Do something
        run: ...
