name: Trigger Workflow in Repo B

on:
  repository_dispatch:
    types:
      - trigger-workflow

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Repo B
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_B_PAT }}
          repository: your-username/repo-b
          event-type: trigger-workflow
